package view;

import java.awt.event.ActionListener;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;

import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

import transporte.QuestionarioTO;

/**
 *
 * @author felip
 */
public class CandidatoFRM extends javax.swing.JFrame {

    /**
     * Creates new form CandidatoFRM
     */
    public CandidatoFRM() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    private DefaultTableModel dataModel;
    private JTable tab;
    private JScrollPane sp;
    private QuestionarioTO questionario;
    private int codCandi;
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

    	
        titulolb = new javax.swing.JLabel();
        btnconsultar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        nomelb = new javax.swing.JLabel();
        nometf = new javax.swing.JTextField();

        titulolb.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        titulolb.setText("Candidato");

        btnconsultar.setText("Consultar");

        btnExcluir.setText("Excluir");

        nomelb.setText("Nome:");

        nometf.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(btnconsultar)
                                .addGap(78, 78, 78)
                                .addComponent(btnExcluir)
                                .addContainerGap(82, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(nomelb)
                                                .addGap(178, 178, 178))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(titulolb)
                                                .addGap(154, 154, 154))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(nometf, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(96, 96, 96))))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(titulolb)
                                .addGap(52, 52, 52)
                                .addComponent(nomelb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nometf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnconsultar)
                                        .addComponent(btnExcluir))
                                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>

    /**
     * @param args the command line arguments
     */
    
    public void addConsultarCandListener(ActionListener listenForConsultarCandButton) {
        this.btnconsultar.addActionListener(listenForConsultarCandButton);
    }
    
    public void addExcluirCandListener(ActionListener listenForExcluirCandButton) {
        this.btnExcluir.addActionListener(listenForExcluirCandButton);
    }
    
    public void limpatela() {
    	nometf.setText("");
    }
    
    

public void econderComponentes(boolean mostrar){
        
        nomelb.setVisible(mostrar);
        nometf.setVisible(mostrar);
       titulolb.setVisible(mostrar);
        
        btnExcluir.setVisible(mostrar);
        btnconsultar.setVisible(mostrar);


    }

public void exibe_tabela(DefaultTableModel dados){
    dataModel = dados;

    if(dataModel != null){
        tab = new JTable(dataModel);
        tab.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        sp = new JScrollPane( tab );
        this.getContentPane().add(sp);
        sp.setBounds(0,0,500,200);

        tab.addKeyListener(new KeyAdapter(){//Tabela "Escuta" o ESC e � ocultada
            @Override
            public void keyPressed(KeyEvent e) {
                if(e.getKeyCode()==27){ //tecla 27 � o ESC
                    sp.setVisible(false);
                    econderComponentes(true);
                }
            }
        });

        ListSelectionModel cel = tab.getSelectionModel();

        cel.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                //Ignore extra messages.
                if (e.getValueIsAdjusting()) return;

                ListSelectionModel lsm = (ListSelectionModel) e.getSource();
                if (!lsm.isSelectionEmpty()) {
                    int selectedRow = tab.getSelectedRow();
                    int selectedCol = tab.getSelectedColumn();

                    String cod = (String) ""+tab.getValueAt(selectedRow,0);
                    int aux_cod = Integer.parseInt(cod);
                    String nome = (String) tab.getValueAt(selectedRow,1);
                    
                    	nometf.setText(nome);
                    		codCandi = aux_cod;
                    		
                    		System.out.println(codCandi);



                    
                    tab.clearSelection();
                    sp.setVisible(false);

                    
                    econderComponentes(true);

                }
            }
        });
    }
}

    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CandidatoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CandidatoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CandidatoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CandidatoFRM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CandidatoFRM().setVisible(true);
            }
        });
    }

    public int getCodCandi() {
		return codCandi;
	}

	public void setCodCandi(int codCandi) {
		this.codCandi = codCandi;
	}

	// Variables declaration - do not modify
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnconsultar;
    private javax.swing.JLabel nomelb;
    private javax.swing.JTextField nometf;
    private javax.swing.JLabel titulolb;
    // End of variables declaration
}
