/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author felip
 */
package view;

import controller.QuestaoController;
import transporte.QuestaoTO;

import javax.swing.*;
import java.awt.event.ActionListener;
import java.util.Vector;

public class ResponderFRM extends javax.swing.JFrame {

    /**
     * Creates new form ResponderFRM
     */

    Vector<QuestaoTO> questaoTOVector = new Vector<>();
    QuestaoController qs = new QuestaoController();
    int i = 0;
    public ResponderFRM() {
        initComponents();
        mostrarTela(false);
        questionariocb.setModel(new javax.swing.DefaultComboBoxModel<>(qs.comboBoxConsulta()));

    }

    public void mostrarTela(boolean oi){
        perguntalb.setVisible(oi);
        proxbutton.setVisible(oi);
        rbuttonA.setVisible(oi);
        rbuttonB.setVisible(oi);
        rbuttonC.setVisible(oi);
        rbuttonD.setVisible(oi);
        quallb.setVisible(!oi);
        questionariocb.setVisible(!oi);
        buttoncontinuar.setVisible(!oi);


    }






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        respostinha = new javax.swing.ButtonGroup();
        questionariocb = new javax.swing.JComboBox<>();
        quallb = new javax.swing.JLabel();
        buttoncontinuar = new javax.swing.JButton();
        perguntalb = new javax.swing.JLabel();
        rbuttonC = new javax.swing.JRadioButton();
        rbuttonA = new javax.swing.JRadioButton();
        rbuttonB = new javax.swing.JRadioButton();
        rbuttonD = new javax.swing.JRadioButton();
        proxbutton = new javax.swing.JButton();

        

        questionariocb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        quallb.setText("Qual prova você vai fazer");

        buttoncontinuar.setText("Continuar");

        perguntalb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        perguntalb.setText("(PERGUNTA)");

        respostinha.add(rbuttonC);
        rbuttonC.setText("C");

        respostinha.add(rbuttonA);
        rbuttonA.setText("A");

        respostinha.add(rbuttonB);
        rbuttonB.setText("B");

        respostinha.add(rbuttonD);
        rbuttonD.setText("D");

        proxbutton.setText("Proxima Questão");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(126, 126, 126)
                                                .addComponent(quallb))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(126, 126, 126)
                                                .addComponent(proxbutton))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(153, 153, 153)
                                                .addComponent(questionariocb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(141, 141, 141)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(buttoncontinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(perguntalb)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(60, 60, 60)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(rbuttonB)
                                                        .addComponent(rbuttonA)
                                                        .addComponent(rbuttonD)
                                                        .addComponent(rbuttonC))))
                                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(quallb)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(questionariocb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(7, 7, 7)
                                .addComponent(buttoncontinuar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(perguntalb)
                                .addGap(13, 13, 13)
                                .addComponent(rbuttonA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbuttonB)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                                .addComponent(rbuttonC)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbuttonD)
                                .addGap(32, 32, 32)
                                .addComponent(proxbutton)
                                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>

    /**
     * @ the command line arguments
     */

    public int getRespostacorreta() {
        if (rbuttonA.isSelected()){
            return 1;
        }
        if (rbuttonB.isSelected()){
            return 2;
        }
        if (rbuttonC.isSelected()){
            return 3;
        }
        if (rbuttonD.isSelected()){
            return 4;
        }
        return 0;
    }

    public void addContinuarListener(ActionListener listenForContinuarButton) {
        this.buttoncontinuar.addActionListener(listenForContinuarButton);
    }

    public void addProximaListener(ActionListener listenForProximaButton) {
        this.proxbutton.addActionListener(listenForProximaButton);
    }

    public String getQuestionariocb() {
        return (String) "" + questionariocb.getSelectedItem();
    }

    public void setPerguntalb(String perguntalb) {
        this.perguntalb.setText(perguntalb);
    }

    public void setAlb(String perguntalb) {
        this.rbuttonA.setText(perguntalb);
    }
    public void setBlb(String perguntalb) {
        this.rbuttonB.setText(perguntalb);
    }
    public void setClb(String perguntalb) {
        this.rbuttonC.setText(perguntalb);
    }
    public void setDlb(String perguntalb) {
        this.rbuttonD.setText(perguntalb);
    }



    public int getI() {
        return i;
    }

    public void setI() {
        this.i = this.i + 1;
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttoncontinuar;
    private javax.swing.JLabel perguntalb;
    private javax.swing.JButton proxbutton;
    private javax.swing.JLabel quallb;
    private javax.swing.JComboBox<String> questionariocb;
    private javax.swing.JRadioButton rbuttonA;
    private javax.swing.JRadioButton rbuttonB;
    private javax.swing.JRadioButton rbuttonC;
    private javax.swing.JRadioButton rbuttonD;
    private javax.swing.ButtonGroup respostinha;
    // End of variables declaration
}
